// <auto-generated />
namespace ASPNET_MVC_ANGULAR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Novo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Novo));
        
        string IMigrationMetadata.Id
        {
            get { return "201702052059083_Novo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
